name: pandas-dev
channels:
  - defaults
dependencies:
  - python=3.7.*

  # tools
  - pytest>=5.0.1
  - pytest-xdist>=1.21
  - hypothesis>=3.58.0
  - pytest-azurepipelines

  # pandas dependencies
  - pytz
  - pip
  - pip:
    - cython==0.29.16
    # GH#33507 cython 3.0a1 is causing TypeErrors 2020-04-13
    - "git+git://github.com/dateutil/dateutil.git"
    - "-f https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com"
    - "--pre"
    - "numpy"
    - "scipy"
